"use client";
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";

export default function DownloadSummaryButton({
  fileName,
  title,
  summaryText,
  createdAt,
}: {
  fileName: string;
  title: string;
  summaryText: string;
  createdAt: string;
}) {
  const handleDownload = () => {
    const summaryContent = `# ${title}
        Generated Summary ${summaryText}
        Generated On ${new Date(createdAt).toLocaleDateString()}
        ${summaryText}
        Original File ${fileName}
        Generated By Quick Sheet`;

    // const blob = new Blob(arrayOfData, { type: "mime/type" });
    const blob = new Blob([summaryContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = url;
    link.download = `Summary-${title.replace(/[^a-z0-9]/gi, "_")}.txt`;
    document.body.appendChild(link);
    link.click();

    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };
  return (
    <Button
      size={"sm"}
      className="h-8 cursor-pointer bg-blue-100 px-3 text-blue-600 hover:bg-blue-50 hover:text-blue-700"
      onClick={handleDownload}
    >
      <Download className="mr-1 h-4 w-4" /> Download Summary
    </Button>
  );
}
